spring.application.name=authentification-service

server.port=8081
#Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_stn_auth_db
spring.datasource.username=postgres
spring.datasource.password=passer
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuration JPA / Hibernate (création automatique des tables SQL)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
#Execution automatique de data.sql au démarrage pour insérer les rôles
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
#Configuration Keycloak (OAuth2 Ressource sever JWT)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/lab-stn-realm
#Clé secrète et expiration JWT local
jwt.secret=9a2f8c4e7b1d3a5f6e8c0b2d4f6a8c1e3b5d7f9a2b4c6d8e0f1a3c5b7d9e2f4
jwt.expiration=86400000
