# =====================================================
# Application Document Service
# =====================================================
spring.application.name=document-service
server.port=8083

# =====================================================
# Base de données PostgreSQL
# =====================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_stn_document
spring.datasource.username=postgres
spring.datasource.password=passer
spring.datasource.driver-class-name=org.postgresql.Driver

# =====================================================
# JPA / Hibernate
# =====================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# =====================================================
# File Storage Configuration (Local & MinIO)
# =====================================================
# Choix de la stratégie : 'minio' ou 'local' (actuellement 'local')
storage.type=local

# Configuration MinIO Object Storage
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=stn-documents

file.upload-dir=uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# =====================================================
# Keycloak - Validation des JWT
# =====================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/lab-stn-realm
