spring.application.name=eureka-service
server.port=8761

# Desactivaton de l'auto-enregistremennt pour le sereur Eureka lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false