spring.application.name=eureka-service
server.port=8761

# Désactivation de l'auto-enregistrement pour le serveur Eureka lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
eureka.server.response-cache-update-interval-ms=2000
eureka.server.eviction-interval-timer-in-ms=5000
