# =====================================================
# Application Thesis Service
# =====================================================

spring.application.name=thesis-service
server.port=8082

# =====================================================
# Base de données PostgreSQL
# =====================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/db_stn_thesis
spring.datasource.username=postgres
spring.datasource.password=passer
spring.datasource.driver-class-name=org.postgresql.Driver

# =====================================================
# JPA / Hibernate
# =====================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# =====================================================
# Keycloak - Validation des JWT
# =====================================================

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/lab-stn-realm
