spring.application.name=user-manager-service
server.port=8081
spring.config.import=optional:configserver:http://localhost:8888
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_stn_auth_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/lab-stn-realm
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
keycloak.server-url=http://localhost:8080
keycloak.realm=lab-stn-realm
keycloak.client-id=stn-user-manager
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
