# =====================================================
# Application
# =====================================================

spring.application.name=user-manager-service
server.port=8081


# =====================================================
# Base de données PostgreSQL
# =====================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/lab_stn_auth_db
spring.datasource.username=postgres
spring.datasource.password=passer
spring.datasource.driver-class-name=org.postgresql.Driver


# =====================================================
# JPA / Hibernate
# =====================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# =====================================================
# Keycloak - Validation des JWT
# =====================================================

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/lab-stn-realm


# =====================================================
# Keycloak - Administration du realm
# =====================================================

keycloak.server-url=http://localhost:8080
keycloak.realm=lab-stn-realm
keycloak.client-id=user-manager-admin
keycloak.client-secret=p1ME0tvCsDM5mOyS32i6gaVPHyL6avhfdLkfij59vYAB7OQZbZIQ7dFLocyk7n5Skn1J55VOisZfivFRaogUp7