# =====================================================
# Application User Manager Service
# =====================================================
server.port=8081
spring.application.name=user-manager-service

# Base de donn�es PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_stn_auth_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/lab-stn-realm
keycloak.server-url=http://localhost:8080
keycloak.realm=lab-stn-realm
keycloak.client-id=user-manager-admin
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.client.registry-fetch-interval-seconds=3
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10

# Tracabilit� Zipkin & Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
